[camera]
position = [0.0, 2.0, -6.0]
direction = [0.0, -1.0, 6.0]
sensor_distance = 0.9
exposure_time = 0.2
aperture = 0.1
focus_distance = 6.08
ldr_scale = 1.0

bounce_limit = 10
num_samples = 1000
width = 512
height = 400

[[lights]]
kind = "Hdri"
path = "assets/pizzo_pernice_1k.exr"
strength = 1.0

#[[lights]]
#kind = "Direction"
#direction = [-0.3, -1.0, -1.0]
#color = [10.0, 10.0, 10.0]

#[[lights]]
#kind = "Area"
#position = [0.0, 4.0, 0.0]
#shape = { kind = "Sphere", radius = 1.0 }
#color = [1.0, 1.0, 1.0]

#[[lights]]
#kind = "Area"
#position = [8.0, 1.0, 0.0]
#shape = { kind = "Sphere", radius = 1.0 }
#color = [2.0, 1.0, 1.0]

# Small shiny non-metallic sphere far
[[objects]]
shape = { kind = "Sphere", radius = 0.3 }
position = [-0.5, 1.0, -5.0]

[objects.material]
base_color = [0.8, 1.0, 0.8]
subsurface = 0.0
metallic = 0.0
specular = 0.4
specular_tint = 0.0
roughness = 0.3
anisotropic = 0.0
sheen = 0.0
sheen_tint = 0.0
clearcoat = 0.0
clearcoat_gloss = 0.0
transmission = 0.0
ior = 1.5

[[objects]]
shape = { kind = "Sphere", radius = 1.0 }
position = [0.0, 1.0, 0.0]

[objects.material]
base_color = [1.0, 1.0, 1.0]
subsurface = 0.0
metallic = 0.0
specular = 0.2
specular_tint = 0.0
roughness = 0.0
anisotropic = 0.0
sheen = 0.0
sheen_tint = 0.0
clearcoat = 0.0
clearcoat_gloss = 0.0
transmission = 1.0
ior = 1.5

# roughish non-metallic sphere
[[objects]]
shape = { kind = "Sphere", radius = 1.0 }
position = [-4.0, 1.0, 0.0]

[objects.material]
base_color = [0.8, 0.5, 1.0]
subsurface = 0.0
metallic = 0.0
specular = 0.4
specular_tint = 0.0
roughness = 0.4
anisotropic = 0.0
sheen = 0.0
sheen_tint = 0.0
clearcoat = 0.0
clearcoat_gloss = 0.0
transmission = 0.0
ior = 1.5

# Metallic sphere
[[objects]]
shape = { kind = "Sphere", radius = 1.0 }
position = [-2.0, 1.0, 0.0]

[objects.material]
base_color = [1.0, 0.7, 0.3]
subsurface = 0.0
metallic = 1.0
specular = 0.2
specular_tint = 0.0
roughness = 0.0
anisotropic = 0.0
sheen = 0.0
sheen_tint = 0.0
clearcoat = 0.0
clearcoat_gloss = 0.0
transmission = 0.0
ior = 1.5

# rough sphere
[[objects]]
shape = { kind = "Sphere", radius = 1.0 }
position = [2.0, 1.0, 0.0]
motion = [0.0, 1.0, 0.0]

[objects.material]
base_color = [0.3, 1.0, 0.8]
subsurface = 0.0
metallic = 0.0
specular = 0.4
specular_tint = 0.0
roughness = 0.8
anisotropic = 0.0
sheen = 0.0
sheen_tint = 0.0
clearcoat = 0.0
clearcoat_gloss = 0.0
transmission = 0.0
ior = 1.5

# texture sphere
[[objects]]
shape = { kind = "Sphere", radius = 1.0 }
position = [4.0, 1.0, 0.0]

[objects.material]
base_color = "assets/Marble13/Marble13_COL_3K.jpg"
subsurface = 0.0
metallic = 0.0
specular = 0.0
specular_tint = 0.0
roughness = 0.0
anisotropic = 0.0
sheen = 0.0
sheen_tint = 0.0
clearcoat = 0.0
clearcoat_gloss = 0.0
transmission = 0.0
ior = 1.5

# Big Sphere
[[objects]]
shape = { kind = "Sphere", radius = 10000.0 }
position = [0.0, -10000.0, 0.0]

[objects.material]
base_color = [0.6, 0.6, 0.6]
subsurface = 0.0
metallic = 0.0
specular = 0.0
specular_tint = 0.0
roughness = 1.0
anisotropic = 0.0
sheen = 0.0
sheen_tint = 0.0
clearcoat = 0.0
clearcoat_gloss = 0.0
transmission = 0.0
ior = 1.5
