[camera]
position = [0.0, 1.0, -3.0]
direction = [0.0, -1.0, 3.0]
sensor_distance = 0.66
hdri = "assets/pizzo_pernice_1k.exr"
hdri_bias = [615, 105]

bounce_limit = 10
num_samples = 1000
width = 512
height = 400

# Small sphere
[[objects]]
shape = 1.0 # sphere rad=1.0
position = [0.0, 1.0, 0.0]

[objects.material]
base_color = [0.8, 0.8, 1.0]
subsurface = 0.0
metallic = 0.0
specular = 0.1
specular_tint = 0.0
roughness = 0.0
anisotropic = 0.0
sheen = 0.0
sheen_tint = 0.0
clearcoat = 0.0
clearcoat_gloss = 0.0

# Metallic sphere
[[objects]]
shape = 1.0 # sphere rad=1.0
position = [-2.0, 1.0, 0.0]

[objects.material]
base_color = [1.0, 1.0, 0.3]
subsurface = 0.0
metallic = 1.0
specular = 1.0
specular_tint = 0.0
roughness = 0.0
anisotropic = 0.0
sheen = 0.0
sheen_tint = 0.0
clearcoat = 0.0
clearcoat_gloss = 0.0

# rough sphere
[[objects]]
shape = 1.0 # sphere rad=1.0
position = [2.0, 1.0, 0.0]

[objects.material]
base_color = [1.0, 1.0, 0.3]
subsurface = 0.0
metallic = 0.0
specular = 1.0
specular_tint = 0.0
roughness = 0.8
anisotropic = 0.0
sheen = 0.0
sheen_tint = 0.0
clearcoat = 0.0
clearcoat_gloss = 0.0

# Big Sphere
[[objects]]
shape = 100.0 # sphere rad=1.0
position = [0.0, -100.0, 0.0]

[objects.material]
base_color = [0.8, 1.0, 0.8]
subsurface = 0.0
metallic = 0.0
specular = 0.0
specular_tint = 0.0
roughness = 1.0
anisotropic = 0.0
sheen = 0.0
sheen_tint = 0.0
clearcoat = 0.0
clearcoat_gloss = 0.0